import { Food } from '@/types';

export const foodsData: Food[] = [
  // 主食类
  {
    id: '1',
    name: { zh: '米饭', en: 'Rice' },
    category: 'staple',
    calories: 130,
    macros: { carbs: 28, protein: 2.7, fat: 0.3, fiber: 0.4 },
    unit: 'g',
  },
  {
    id: '2',
    name: { zh: '面条', en: 'Noodles' },
    category: 'staple',
    calories: 137,
    macros: { carbs: 25, protein: 4.5, fat: 2.1, fiber: 1.2 },
    unit: 'g',
  },
  {
    id: '3',
    name: { zh: '馒头', en: 'Steamed Bun' },
    category: 'staple',
    calories: 223,
    macros: { carbs: 47, protein: 7, fat: 1.1, fiber: 1.3 },
    unit: 'g',
  },
  {
    id: '4',
    name: { zh: '燕麦片', en: 'Oatmeal' },
    category: 'staple',
    calories: 389,
    macros: { carbs: 66, protein: 16.9, fat: 6.9, fiber: 10.6 },
    unit: 'g',
  },
  {
    id: '5',
    name: { zh: '全麦面包', en: 'Whole Wheat Bread' },
    category: 'staple',
    calories: 247,
    macros: { carbs: 41, protein: 13, fat: 3.4, fiber: 7 },
    unit: 'g',
  },
  {
    id: '6',
    name: { zh: '红薯', en: 'Sweet Potato' },
    category: 'staple',
    calories: 86,
    macros: { carbs: 20, protein: 1.6, fat: 0.1, fiber: 3 },
    unit: 'g',
  },
  {
    id: '7',
    name: { zh: '玉米', en: 'Corn' },
    category: 'staple',
    calories: 112,
    macros: { carbs: 22.8, protein: 3.3, fat: 1.2, fiber: 2.7 },
    unit: 'g',
  },
  {
    id: '8',
    name: { zh: '小米粥', en: 'Millet Porridge' },
    category: 'staple',
    calories: 46,
    macros: { carbs: 9.3, protein: 1.2, fat: 0.3, fiber: 0.4 },
    unit: 'g',
  },
  // 肉类
  {
    id: '9',
    name: { zh: '鸡胸肉', en: 'Chicken Breast' },
    category: 'meat',
    calories: 165,
    macros: { carbs: 0, protein: 31, fat: 3.6, fiber: 0 },
    unit: 'g',
  },
  {
    id: '10',
    name: { zh: '牛肉', en: 'Beef' },
    category: 'meat',
    calories: 250,
    macros: { carbs: 0, protein: 26, fat: 17, fiber: 0 },
    unit: 'g',
  },
  {
    id: '11',
    name: { zh: '猪肉', en: 'Pork' },
    category: 'meat',
    calories: 242,
    macros: { carbs: 0, protein: 27, fat: 14, fiber: 0 },
    unit: 'g',
  },
  {
    id: '12',
    name: { zh: '三文鱼', en: 'Salmon' },
    category: 'meat',
    calories: 208,
    macros: { carbs: 0, protein: 20, fat: 13, fiber: 0 },
    unit: 'g',
  },
  {
    id: '13',
    name: { zh: '鸡蛋', en: 'Egg' },
    category: 'meat',
    calories: 155,
    macros: { carbs: 1.1, protein: 13, fat: 11, fiber: 0 },
    unit: 'g',
  },
  {
    id: '14',
    name: { zh: '虾仁', en: 'Shrimp' },
    category: 'meat',
    calories: 99,
    macros: { carbs: 0.2, protein: 24, fat: 0.3, fiber: 0 },
    unit: 'g',
  },
  {
    id: '15',
    name: { zh: '豆腐', en: 'Tofu' },
    category: 'meat',
    calories: 76,
    macros: { carbs: 1.9, protein: 8, fat: 4.8, fiber: 0.3 },
    unit: 'g',
  },
  // 蔬菜类
  {
    id: '16',
    name: { zh: '西兰花', en: 'Broccoli' },
    category: 'vegetable',
    calories: 34,
    macros: { carbs: 7, protein: 2.8, fat: 0.4, fiber: 2.6 },
    unit: 'g',
  },
  {
    id: '17',
    name: { zh: '菠菜', en: 'Spinach' },
    category: 'vegetable',
    calories: 23,
    macros: { carbs: 3.6, protein: 2.9, fat: 0.4, fiber: 2.2 },
    unit: 'g',
  },
  {
    id: '18',
    name: { zh: '黄瓜', en: 'Cucumber' },
    category: 'vegetable',
    calories: 16,
    macros: { carbs: 3.6, protein: 0.7, fat: 0.1, fiber: 0.5 },
    unit: 'g',
  },
  {
    id: '19',
    name: { zh: '番茄', en: 'Tomato' },
    category: 'vegetable',
    calories: 18,
    macros: { carbs: 3.9, protein: 0.9, fat: 0.2, fiber: 1.2 },
    unit: 'g',
  },
  {
    id: '20',
    name: { zh: '胡萝卜', en: 'Carrot' },
    category: 'vegetable',
    calories: 41,
    macros: { carbs: 9.6, protein: 0.9, fat: 0.2, fiber: 2.8 },
    unit: 'g',
  },
  {
    id: '21',
    name: { zh: '青椒', en: 'Green Pepper' },
    category: 'vegetable',
    calories: 22,
    macros: { carbs: 4.6, protein: 0.9, fat: 0.2, fiber: 1.7 },
    unit: 'g',
  },
  {
    id: '22',
    name: { zh: '白菜', en: 'Chinese Cabbage' },
    category: 'vegetable',
    calories: 13,
    macros: { carbs: 2.2, protein: 1.1, fat: 0.2, fiber: 1 },
    unit: 'g',
  },
  {
    id: '23',
    name: { zh: '生菜', en: 'Lettuce' },
    category: 'vegetable',
    calories: 15,
    macros: { carbs: 2.9, protein: 1.4, fat: 0.2, fiber: 1.3 },
    unit: 'g',
  },
  // 水果类
  {
    id: '24',
    name: { zh: '苹果', en: 'Apple' },
    category: 'fruit',
    calories: 52,
    macros: { carbs: 14, protein: 0.3, fat: 0.2, fiber: 2.4 },
    unit: 'g',
  },
  {
    id: '25',
    name: { zh: '香蕉', en: 'Banana' },
    category: 'fruit',
    calories: 89,
    macros: { carbs: 23, protein: 1.1, fat: 0.3, fiber: 2.6 },
    unit: 'g',
  },
  {
    id: '26',
    name: { zh: '橙子', en: 'Orange' },
    category: 'fruit',
    calories: 47,
    macros: { carbs: 12, protein: 0.9, fat: 0.1, fiber: 2.4 },
    unit: 'g',
  },
  {
    id: '27',
    name: { zh: '葡萄', en: 'Grapes' },
    category: 'fruit',
    calories: 69,
    macros: { carbs: 18, protein: 0.7, fat: 0.2, fiber: 0.9 },
    unit: 'g',
  },
  {
    id: '28',
    name: { zh: '草莓', en: 'Strawberry' },
    category: 'fruit',
    calories: 32,
    macros: { carbs: 7.7, protein: 0.7, fat: 0.3, fiber: 2 },
    unit: 'g',
  },
  {
    id: '29',
    name: { zh: '西瓜', en: 'Watermelon' },
    category: 'fruit',
    calories: 30,
    macros: { carbs: 8, protein: 0.6, fat: 0.2, fiber: 0.4 },
    unit: 'g',
  },
  {
    id: '30',
    name: { zh: '牛油果', en: 'Avocado' },
    category: 'fruit',
    calories: 160,
    macros: { carbs: 9, protein: 2, fat: 15, fiber: 7 },
    unit: 'g',
  },
  {
    id: '31',
    name: { zh: '蓝莓', en: 'Blueberry' },
    category: 'fruit',
    calories: 57,
    macros: { carbs: 14, protein: 0.7, fat: 0.3, fiber: 2.4 },
    unit: 'g',
  },
  // 零食/饮品
  {
    id: '32',
    name: { zh: '酸奶', en: 'Yogurt' },
    category: 'snack',
    calories: 72,
    macros: { carbs: 9, protein: 4.3, fat: 2.1, fiber: 0 },
    unit: 'g',
  },
  {
    id: '33',
    name: { zh: '牛奶', en: 'Milk' },
    category: 'beverage',
    calories: 54,
    macros: { carbs: 4.8, protein: 3.4, fat: 3, fiber: 0 },
    unit: 'ml',
  },
  {
    id: '34',
    name: { zh: '豆浆', en: 'Soy Milk' },
    category: 'beverage',
    calories: 31,
    macros: { carbs: 1.8, protein: 2.9, fat: 1.6, fiber: 0.3 },
    unit: 'ml',
  },
  {
    id: '35',
    name: { zh: '坚果混合', en: 'Mixed Nuts' },
    category: 'snack',
    calories: 607,
    macros: { carbs: 21, protein: 20, fat: 54, fiber: 8 },
    unit: 'g',
  },
  {
    id: '36',
    name: { zh: '黑巧克力', en: 'Dark Chocolate' },
    category: 'snack',
    calories: 546,
    macros: { carbs: 61, protein: 4.9, fat: 31, fiber: 7 },
    unit: 'g',
  },
  {
    id: '37',
    name: { zh: '咖啡', en: 'Coffee' },
    category: 'beverage',
    calories: 2,
    macros: { carbs: 0.3, protein: 0.3, fat: 0, fiber: 0 },
    unit: 'ml',
  },
  {
    id: '38',
    name: { zh: '绿茶', en: 'Green Tea' },
    category: 'beverage',
    calories: 1,
    macros: { carbs: 0.2, protein: 0.1, fat: 0, fiber: 0 },
    unit: 'ml',
  },
  {
    id: '39',
    name: { zh: '橙汁', en: 'Orange Juice' },
    category: 'beverage',
    calories: 45,
    macros: { carbs: 10, protein: 0.7, fat: 0.2, fiber: 0.2 },
    unit: 'ml',
  },
  {
    id: '40',
    name: { zh: '可乐', en: 'Cola' },
    category: 'beverage',
    calories: 42,
    macros: { carbs: 10.6, protein: 0, fat: 0, fiber: 0 },
    unit: 'ml',
  },
];

export const foodCategories = [
  { id: 'all', name: { zh: '全部', en: 'All' } },
  { id: 'staple', name: { zh: '主食', en: 'Staple' } },
  { id: 'meat', name: { zh: '肉类', en: 'Meat' } },
  { id: 'vegetable', name: { zh: '蔬菜', en: 'Vegetable' } },
  { id: 'fruit', name: { zh: '水果', en: 'Fruit' } },
  { id: 'snack', name: { zh: '零食', en: 'Snack' } },
  { id: 'beverage', name: { zh: '饮品', en: 'Beverage' } },
] as const;
